default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("MYSQL_PORT", 3306) %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  primary:
    <<: *default
    database: myapp_production

  cache:
    <<: *default
    database: myapp_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: myapp_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: myapp_production_cable
    migrations_paths: db/cable_migrate
